<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Microsoft.Extensions.Logging" />
        <Using Include="Shared" />
        <Using Include="Helpers" />
        <Using Include="WarpCoreController" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="SixLabors.ImageSharp" Version="1.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Helpers\Helpers.csproj" />
        <ProjectReference Include="..\rpi_kens\rpi_kens.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
