PENDING_CRLF_DELAY_SEC = 0.1
BYTE_CR = 0x0D
BYTE_LF = 0x0A

SER_PROTO_DIAGS = 2
SER_PROTO_RESPONSE_DELIMITER = "|"

SER_PROTO_INIT_HEADER = "SP_INIT"
SER_PROTO_INIT_RESPONSE = "SP_READY"
SER_PROTO_OK = "SP_OK"
SER_PROTO_ERR = "SP_ERR"

SER_PROTO_QUERY = "_QUERY"
SER_PROTO_RESPONSE = "_RESPONSE"
SER_PROTO_SET = "_SET"

SER_PROTO_ENGINE_POWER = "SP_ENG_POWER"
SER_PROTO_ENGINE_POWER_QUERY = SER_PROTO_ENGINE_POWER + SER_PROTO_QUERY
SER_PROTO_ENGINE_POWER_RESPONSE = SER_PROTO_ENGINE_POWER + SER_PROTO_RESPONSE
SER_PROTO_ENGINE_POWER_SET = SER_PROTO_ENGINE_POWER + SER_PROTO_SET

SER_PROTO_TRANSFORMER_POWER = "SP_TRANS_POWER"
SER_PROTO_TRANSFORMER_POWER_QUERY = SER_PROTO_TRANSFORMER_POWER + SER_PROTO_QUERY
SER_PROTO_TRANSFORMER_POWER_RESPONSE = SER_PROTO_TRANSFORMER_POWER + SER_PROTO_RESPONSE
SER_PROTO_TRANSFORMER_POWER_SET = SER_PROTO_TRANSFORMER_POWER + SER_PROTO_SET

SER_PROTO_SYSTEM_POWER = "SP_SYS_POWER"
SER_PROTO_SYSTEM_POWER_QUERY = SER_PROTO_SYSTEM_POWER + SER_PROTO_QUERY
SER_PROTO_SYSTEM_POWER_RESPONSE = SER_PROTO_SYSTEM_POWER + SER_PROTO_RESPONSE
SER_PROTO_SYSTEM_POWER_SET = SER_PROTO_SYSTEM_POWER + SER_PROTO_SET
