<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
        <Using Include="Microsoft.Extensions.Logging" />
        <Using Include="Newtonsoft.Json" />
        <Using Include="Helpers" />
        <Using Include="engine_sim.Shared" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.JSON" Version="13.0.1" />
        <PackageReference Include="Serilog" Version="2.10.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="5.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
        <PackageReference Include="serilog.expressions" Version="3.3.0" />
        <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="4.0.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.0" />
        <PackageReference Include="System.IO.Ports" Version="6.0.0" />
        <PackageReference Include="System.Management" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Helpers\Helpers.csproj" />
        <ProjectReference Include="..\Shared\engine_sim.Shared.csproj" />
    </ItemGroup>

</Project>
