; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = feather_m4

[env:due]
platform = atmelsam
board = due
framework = arduino
lib_deps = 
	fastled/FastLED@^3.4.0
	thomasfredericks/Bounce2@^2.70
monitor_speed = 115200
extra_scripts = no_verify.py

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
lib_deps = 
	fastled/FastLED@^3.4.0
	thomasfredericks/Bounce2@^2.70

[env:feather_m4]
platform = atmelsam
board = adafruit_feather_m4
framework = arduino
monitor_speed = 115200
lib_deps = 
	fastled/FastLED@^3.4.0
	thomasfredericks/Bounce2@^2.70
