<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Newtonsoft.Json" />
        <Using Include="SSG.Shared" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Flurl.Http" Version="3.2.4" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.9" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />
        <PackageReference Include="MudBlazor" Version="6.0.16" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SSG.Shared\SSG.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Exclude all items from being watched. -->
        <!-- <Compile Update="@(Compile)" Watch="false" /> -->
        <Content Update="@(Content)" Watch="false" />

        <!-- Then add them back in with exclusions for the webpack files -->
        <Watch Include="@(Content)" Exclude="wwwroot/**/*.css.map;wwwroot/**/*.scss;wwwroot/**/*.ts" />
    </ItemGroup>

    <Target Name="DumpDiags">
        <Message Text="Compile item type contains:" />
        <Message Text="@(Compile, '%0D')" />
        <Message Text="~~~~~~~~~~~~~~~~~~~~~~~~" />
        <Message Text="EmbeddedResource item type contains:" />
        <Message Text="@(EmbeddedResource, '%0D')" />
        <Message Text="~~~~~~~~~~~~~~~~~~~~~~~~" />
        <Message Text="MSBuildProjectFiles item type contains:" />
        <Message Text="@(MSBuildProjectFiles, '%0D')" />
        <Message Text="~~~~~~~~~~~~~~~~~~~~~~~~" />
        <Message Text="Watch item type contains:" />
        <Message Text="@(Watch, '%0D')" />
    </Target>
</Project>