<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Newtonsoft.Json" />
        <Using Include="SSG.Shared" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.9" PrivateAssets="all" />
        <PackageReference Include="MudBlazor" Version="6.0.16" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SSG.Shared\SSG.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Exclude all Content items from being watched. -->
        <Content Update="@(Content)" Watch="false" />
        <Watch Include="wwwroot/index.html;wwwroot/css/*.css;wwwroot/public/*" />
    </ItemGroup>

    <Target Name="DumpDiags">
        <Message Text="Compile item type contains:" />
        <Message Text="@(Compile, '%0D')" />
        <Message Text="   " />
        <Message Text="EmbeddedResource item type contains:" />
        <Message Text="@(EmbeddedResource, '%0D')" />
        <Message Text="   " />
        <Message Text="Watch item type contains:" />
        <Message Text="@(Watch, '%0D')" />
    </Target>
</Project>