<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

    <ItemGroup>
        <Using Include="Microsoft.Extensions.Logging" />
        <Using Include="Shared" />
        <Using Include="Helpers" />
    </ItemGroup>

    <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\Shared\engine-sim.Shared.csproj" />
  </ItemGroup>

</Project>
