<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
	
    <ItemGroup>
        <Using Include="System.Numerics" />
        <Using Include="Newtonsoft.Json" />
        <Using Include="Serilog" />
        <Using Remove="Microsoft.Extensions.Logging" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageReference Include="Serilog" Version="2.10.0" />
        <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    </ItemGroup>
</Project>
