from color_utils import Color

class PowerCardCategories:
    OFF_COLOR = Color("#000000")
    POWER_SYSTEMS_COLOR = Color("#00B428")
    DEFENSIVE_SYSTEMS_COLOR = Color("#005AFF")
    WEAPONS_SYSTEMS_COLOR = Color("#FF2814")
    PROPULSION_SYSTEMS_COLOR = Color("#FF9600")
    INFORMATION_SYSTEMS_COLOR = Color("#8C28FF")
    UTILITY_SYSTEMS_COLOR = Color("#E8B998")

    POWER_SYSTEMS_CATEGORY_NAME = "Power & Core Systems"
    DEFENSIVE_SYSTEMS_CATEGORY_NAME = "Defensive Systems"
    WEAPONS_SYSTEMS_CATEGORY_NAME = "Weapons Systems"
    PROPULSION_SYSTEMS_CATEGORY_NAME = "Propulsion & Movement"
    INFORMATION_SYSTEMS_CATEGORY_NAME = "Information Systems"
    UTILITY_SYSTEMS_CATEGORY_NAME = "Utility Systems"

    CATEGORY_COLORS = {
        POWER_SYSTEMS_CATEGORY_NAME: POWER_SYSTEMS_COLOR,
        DEFENSIVE_SYSTEMS_CATEGORY_NAME: DEFENSIVE_SYSTEMS_COLOR,
        WEAPONS_SYSTEMS_CATEGORY_NAME: WEAPONS_SYSTEMS_COLOR,
        PROPULSION_SYSTEMS_CATEGORY_NAME: PROPULSION_SYSTEMS_COLOR,
        INFORMATION_SYSTEMS_CATEGORY_NAME: INFORMATION_SYSTEMS_COLOR,
        UTILITY_SYSTEMS_CATEGORY_NAME: UTILITY_SYSTEMS_COLOR,
    }
